name: Deploy do Canônico (Java & NPM)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github

      # --- EXTRAÇÃO DE VERSÃO (O PULO DO GATO) ---
      - name: Get Maven Version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "::notice::Versão detectada no POM: $VERSION"

      # --- ETAPA JAVA ---
      - name: Build and Publish Java Jar
        run: |
          echo "::group::🚀 Iniciando Build Maven"
          mvn --batch-mode clean deploy -s /home/runner/.m2/settings.xml
          echo "::notice::Deploy do JAR finalizado com sucesso no GitHub Packages!"
          echo "::endgroup::"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@xcorpiiion'

      # --- ETAPA NPM (TS) ---
      - name: Publish NPM Package
        run: |
          echo "::group::📦 Preparando Pacote NPM v${{ steps.get_version.outputs.PROJECT_VERSION }}"
          
          cd target/generated-ts
          
          if [ -f "models.ts" ]; then
            echo "::notice::Arquivo models.ts encontrado!"
          else
            echo "::error::Arquivo models.ts não foi gerado pelo Maven! Verifique o plugin no pom.xml"
            exit 1
          fi

          echo "Criando package.json dinâmico com a versão do Maven..."
          echo '{
            "name": "@xcorpiiion/canonico-ts",
            "version": "${{ steps.get_version.outputs.PROJECT_VERSION }}",
            "description": "Classes Canônicas v${{ steps.get_version.outputs.PROJECT_VERSION }}",
            "main": "models.ts",
            "repository": {
              "type": "git",
              "url": "git+https://github.com/xcorpiiion/canonico-microservico.git"
            },
            "publishConfig": {
              "registry": "https://npm.pkg.github.com"
            }
          }' > package.json

          echo "Iniciando o publish no registro do GitHub..."
          npm publish
          
          echo "::notice::Lib v${{ steps.get_version.outputs.PROJECT_VERSION }} publicada com sucesso!"
          echo "::endgroup::"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}